### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ElMay0r** [iiegor/slither#17] opened 2016-04-19 06:40 UTC
[Server][ERROR] Unhandled message s -  null
Snake going to 250
[Server][ERROR] Unhandled message s -  null
[Server][ERROR] Unhandled message s -  null

**Comment by morenja** [comment] 2016-04-19 13:31
Me too have that problem, and you can't move?

**Comment by thereis** [comment] 2016-04-19 14:56
The problem is not solved, it will be solved after some updates...

**Comment by iiegor** [comment] 2016-04-19 15:23
@thereis that's, closing this.

**Closed by iiegor** 2016-04-19 15:23 UTC
