### ISSUE TITLE
no food in my map

### ISSUE THREAD

**Issue by ZzerLo** [iiegor/slither#76] opened 2016-05-25 16:56 UTC
there is no food so i cannot do anything besides wander around very fastly........
i would imagine there is something in the code  so food will spawn but i cant find it and im not sure how to work with coffeescript.

**Comment by AlexDicy** [comment] 2016-05-25 20:04
This is a duplicate of #75 and other two issues, It is a known bug and they are working for fix it

**Closed as completed** 2016-05-25 20:12 UTC
